version: "3.8"
services:
  app:
    image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
    ports:
      - "80:80"
      - "8000:8000"
      - "8501:8501" # Expose Streamlit port
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app  # Add /app to the Python path
    restart: unless-stopped
    command: |
      uvicorn talk2sql.app.main:app --host 0.0.0.0 --port 8000 --reload & streamlit run app/frontend/Talk2SQL.py --server.address=0.0.0.0 --server.port=8501