version: '3.8'

services:
  backend:
    image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
    command: streamlit run app/frontend/Talk2SQL.py --server.port 80 --server.address 0.0.0.0
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
