version: "3.8"
services:
  app:
    image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
    ports:
      - "80:8080"  # Map host port 80 to container port 8080
      - "8000:8000"
      - "8501:8501" # Expose Streamlit port
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: |
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload & streamlit run app/frontend/Talk2SQL.py --server.address=0.0.0.0 --server.port=8501