services:
  app:
    image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest  # Pull image from ECR
    ports:
      - "80:80"  # Maps container port 80 (Streamlit frontend) to host port 80. Backend runs internally on port 8000
      - "8000:8000"  # Add this line to expose the FastAPI port
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
